name: Create and Merge Pull Request
on:
  workflow_dispatch:
    inputs:
      feature_branch:
        description: 'Feature branch name'
        required: true
      pr_title:
        description: 'Pull request title'
        required: true

jobs:
  create-and-merge-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Verify Feature Branch
      run: |
        # Fetch the latest information about remote branches
        git fetch --all
        
        # List all branches
        git branch -a
        
        # Get input values
        FEATURE_BRANCH="${{ github.event.inputs.feature_branch }}"
        
        # Check if the feature branch exists 
        if ! git show-ref --verify --quiet "refs/heads/$FEATURE_BRANCH"; then
          echo "Error: Feature branch '$FEATURE_BRANCH' does not exist."
          exit 1
        fi

    - name: PR Title Check
      uses: deepakputhraya/action-pr-title@master
      with:
        regex: '[a-zA-Z]+\/\w+(\-|\.)\S+\s{1}\S*' # Regex the title should match.
        allowed_prefixes: 'feature/MATE-,hotfix/MATE-,release/MATE-,docs/MATE-,test/MATE-,issue/MATE-,bugfix/MATE-' # title should start with the given prefix
        disallowed_prefixes: 'fix,bug' # title should not start with the given prefix
        prefix_case_sensitive: false # title prefix are case insensitive
        min_length: 17 # Min length of the title
        max_length: 80 # Max length of the title

    - name: Create Pull Request
      run: |
        FEATURE_BRANCH="${{ github.event.inputs.feature_branch }}"
        PR_TITLE="${{ github.event.inputs.pr_title }}"
        
        git checkout "$FEATURE_BRANCH"
        
        # Push the changes to the feature branch
        git push origin "$FEATURE_BRANCH"
        
        # Create the pull request
        gh pr create --base release --head "$FEATURE_BRANCH" --title "$PR_TITLE" --body "This pull request was created automatically by a GitHub Action."

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Pull Request
      run: |
        gh pr merge --auto --merge "$FEATURE_BRANCH"
        
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
