# This is a basic workflow to help you get started with Actions

name: Manual Pull Request

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Create and push feature branch
        run: |
          git checkout -b test001
          git push origin test001

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = context.github;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = 'release'; // Set your release branch name
            const head = 'test001'; // Set your feature branch name
            const title = 'Feature: My New Feature'; // Set your PR title

            const response = await github.pulls.create({
              owner,
              repo,
              title,
              head,
              base,
            });

            const prUrl = response.data.html_url;
            console.log(`Pull request created: ${prUrl}`);
      

